### ISSUE TITLE
RainflowCounterFKM - last and first sample point

### ISSUE THREAD

**Issue by alexander-maier** [boschresearch/pylife#4]
Hi,

I get wrong results when using the `stress.rainflow.RainflowCounterFKM` class. The following input should result in one closed loop but does not:

```python
import pylife.stress.rainflow as rainflow

m = np.array([0., 100., 0., 100.])
rfc = rainflow.RainflowCounterFKM().process(m)
print(f"from={rfc.loops_from}", f"to={rfc.loops_to}")
```
Instead `rfc.loops_from` and `rfc.loops_to` are empty. Using the class `rainflow.RainflowCounterThreePoint` the result is the following: `from=[100.0] to=[0.0]`

The following code leads to the same result as `rainflow.RainflowCounterThreePoint`
```python
import pylife.stress.rainflow as rainflow

m = np.array([0., 100., 0., 100., 99.])
rfc = rainflow.RainflowCounterFKM().process(m)
print(f"from={rfc.loops_from}", f"to={rfc.loops_to}")
```

Is this a problem with the `_get_new_turns` method? The method `rainflow.RainflowCounterThreePoint().process` appends the last sample point, while  `stress.rainflow.RainflowCounterFKM().process` does not.

https://github.com/boschresearch/pylife/blob/8b084f12ef3966a21f22fa9cf36bc7b2c714dc10/pylife/stress/rainflow.py#L241

**Comment by johannes-mueller** [comment]
Thanks for your report.

It is known, that the two algorithms behave slightly different regarding the last loop of the signal and the very first sample. Our algorithm would close the last loop in your case. The FKM one leaves it open and close it only when the next actual turn comes along. We left it like that because when you have many loops the difference is not that big.

We could however easily adjust `stress.rainflow.RainflowCounterFKM` so that it will pass the following tests:
```python
def test_rainflow_FKM_one_closed_loop():
    signal = np.array([0., 100., 0., 100.])
    rfc = RF.RainflowCounterFKM().process(signal)

    np.testing.assert_array_equal(rfc.loops_from, np.array([100.]))
    np.testing.assert_array_equal(rfc.loops_to, np.array([0.]))
    np.testing.assert_array_equal(rfc.residuals(), np.array([]))


def test_rainflow_FKM_two_closed_loops():
    signal = np.array([0., 100., 0., 100., 0.])
    rfc = RF.RainflowCounterFKM().process(signal)

    np.testing.assert_array_equal(rfc.loops_from, np.array([100.]))
    np.testing.assert_array_equal(rfc.loops_to, np.array([0.]))
    np.testing.assert_array_equal(rfc.residuals(), np.array([100.]))
```

Would that make sense to you?

**Comment by alexander-maier** [comment]
Thanks for your quick reply. I agree, that the effect of this is neglegdible for most situations. 

My issue is that the FKM one does not loop over the last (and the first) signal point because of the method `self._get_new_turns(samples)`. In other words: the core of the counting algorithm never sees the last and the first signal point. It is therefore less a question of counting per se and more a question of filtering before counting.

Consider the following example. The load sequence `m` is given and looped over for a first and a second time:
```python
m = np.array([100., 0., 200.,0.])
rfc1 = rainflow.RainflowCounterFKM().process(m)
rfc2 = rainflow.RainflowCounterFKM().process(np.concatenate([m, m]))
print(f"from={rfc1.loops_from}", f"to={rfc1.loops_to}", f"res={rfc1._residuals}")
print(f"from={rfc2.loops_from}", f"to={rfc2.loops_to}", f"res={rfc2._residuals}")
```
The result of this is independent of the first signal point `s = 100`, as long it is in the range `0 < s < 200`. The first closed loop (closes when reaching the value 200 with range= 100., mean = 50.) is missing in both cases. 

When extrapolating, this would have a significant influence. As described in the FKM nonlinear, the total number of sustainable repetitions of the load sequence is calculated by solving `D * x + d = 1` for `x`, where `d` is the damage sum of the first and `D` the damage sum of the second repetition of the load signal. Using the proposed algorithm, `x` would be underestimated.

**Comment by johannes-mueller** [comment]
We don't know what was before the first sample. So in your example `[100., 0., 200., 0.]` we actually can't tell whether we close a loop when we reach the `200.`. If the actual load was `[0., 100., 0., 200.0., 0.]` we would close a loop at 200.0, whereas if the load was `[300., 100., 0., 200., 0.]` we would not.

The thing is that `get_turns()` never gives the first sample and the last sample as a turn because we can't tell if the first and the last sample are turns.

You could precondition `rainflow.RainflowCounterFKM` by seaking in a zero sample at the beginning like
```python
rfc = RF.RainflowCounterFKM().process(np.array([0.])).process(m)
```
Then the loop 100 → 0 → 100 would be counted as closed.

Question is whether we always should assume such a zero sample in the beginning. This could be done easily by calling `.process(np.array([0.])` in `rainflow.RainflowCounterFKM.__init__()`. Opinions?

**Comment by alexander-maier** [comment]
I think it would be useful to have two options when initializing `rainflow.RainflowCounterFKM.__init__()`:

1. No input (default): call `.process(np.array([0.])` in `rainflow.RainflowCounterFKM.__init__()`. This would eliminate the (for me) unexpected behavior regarding the first sample point.

2. Initialize with a value for `residuals` and a value for `ir` (optional). These values could also be the default ones (`residuals=[]`, `ir=1`) to get the current behavior.


For the last sample point, we can tell if the loop closes even if we cant tell if its a turning point. But taking this into account may cause a large overhead especially if there are many sample chunks.

**Comment by johannes-mueller** [comment]
Closing this issue in favor of #22.
